### ISSUE TITLE
Using llvm's libunwind vs fixing savannah libunwind vs ?

### ISSUE THREAD

**Issue by tony** [pyston/pyston#1074]
Carried on from #1070, http://blog.kevmod.com/2014/05/update-on-pyston/, https://github.com/dropbox/pyston/blob/master/docs/UNWINDING.md

Currently there are some issues pyston may encounter on OS X and other (to a minor degree) FreeBSD with the libunwind we're using.

There's no resource to get the state of unwinding libraries, [a lonely stackoverflow thread](http://stackoverflow.com/questions/25356691/what-kind-of-stack-unwinding-libraries-do-exist-and-whats-the-difference).

LLVM released their own [libunwind](https://github.com/llvm-mirror/libunwind) [back in 2013](http://blog.llvm.org/2013/10/new-libunwind-implementation-in-libcabi.html), its recently been decoupled into its own project https://llvm.org/bugs/show_bug.cgi?id=23364 ([link to the latest libunwind issues on bugzilla](https://llvm.org/bugs/buglist.cgi?bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&f0=OP&f1=OP&f2=product&f3=component&f4=alias&f5=short_desc&f6=status_whiteboard&f7=content&f8=CP&f9=CP&j1=OR&o2=substring&o3=substring&o4=substring&o5=substring&o6=substring&o7=matches&query_format=advanced&v2=libunwind&v3=libunwind&v4=libunwind&v5=libunwind&v6=libunwind&v7=%22libunwind%22&order=changeddate%20DESC%2Cbug_status%2Cpriority%2Cassigned_to%2Cbug_id&query_based_on=)).

At first glance it seems [llvm's libunwind](https://github.com/llvm-mirror/libunwind) lacks any of the machine dependent code the [current one we're using](http://www.nongnu.org/libunwind/). libunwind does plug into [libcxxabi](https://github.com/llvm-mirror/libcxxabi/search?p=1&q=unwind&utf8=%E2%9C%93). I do see some traces of x86_64 peppered throughout there.

Using libunwind from LLVM may circumvent #1070 and #456. How far behind is LLVM's libunwind from our current libunwind as far as accomplishing the needs of  pyston's custom unwinder?

Do the statements at the top of https://github.com/dropbox/pyston/blob/acc52c0eaa8bac0fdbbf5cb8ecb3c676109748a5/docs/UNWINDING.md (regarding efficiency and customizability) hold true still?  Doesn't using the savannah libunwind mean OS X is a no go? Apple seems to be backing the LLVM implementation.

**Comment by kmod** [comment]
I think the choice of libunwind library is orthogonal from the exception unwinding -- our C++ exception unwinder is built on top of the libunwind API.  I'm not sure if this is what you meant, but I think we will be fine to switch out the libunwind library for a different one without breaking our exception handling.  To answer your last question directly though, no performance isn't as important for unwinding any more now that we support fast return-code exceptions, but Customizability is still important (we could probably find a way around it but it would take time).

I think there isn't any way to know how LLVM's libunwind will work out except by trying it :)  I believe OSX has some sort of implementation of the libunwind API, but when we run it crashes with a message that one of the API functions we use is unsupported.  I think we'll just have to try linking in the LLVM one and see!

**Comment by blakejohnson** [comment]
You may want to also consider:
https://github.com/JuliaLang/libosxunwind

Also based upon Apple's fork, but with some additional fixes for problems we encountered using it with Julia's JIT.
