### ISSUE TITLE
cleanup interned strings which are specified as mortal

### ISSUE THREAD

**Issue by undingen** [pyston/pyston#1193]
currently we convert mortal interned strings ones to inmortal ones. 
I think this is mainly artifact of our previous conservative GC.
Now with reference counting we should be able to switch to cpythons implementation.

**Comment by kmod** [comment]
One hiccup here is that our HiddenClass objects don't incref their string keys, and instead rely on them being immortally interned.  I think the easiest way to handle that for now would be to make sure that they change any mortally-interned strings they receive to immortal.
