### ISSUE TITLE
add missing tp_as_mapping, tp_as_sequence and tp_as_number functions

### ISSUE THREAD

**Issue by undingen** [pyston/pyston#1197]
Some of our builtin types don't overwrite all of this functions. 
This means the perf will be slightly worse because we will call into the slot wrapper which will than do an attribute lookup instead of just calling the function pointer.
One example is our `list` type which does not initialize the `tp_as_mapping` function pointers.
They are therefore initialized to `slot_sq_length`, etc.. while we should overwrite them with custom implementations like `list_length`.

**Comment by undingen** [comment]
I added https://github.com/dropbox/pyston/pull/1198 as an example for such a change.

**Comment by sizeoftank** [comment]
For example ` tp_as_mapping`  in  ` list `,  I think it could completed by copy the implementation from cpython, right?

**Comment by kmod** [comment]
Our list object is very similar to CPython's, so that sounds like a good place to start even if there are small things that might have to be adjusted.
