### ISSUE TITLE
Help us come up with some more macrobenchmarks

### ISSUE THREAD

**Issue by kmod** [pyston/pyston#1224]
We currently have three macro-ish benchmarks in the [pyston-perf](https://github.com/dropbox/pyston-perf) repository.  We would love to have more.  If you have a Python application whose performance is important to you, it'd be great if it could be made into a benchmark and added to our suite.

**Comment by wscullin** [comment]
Is there a preference that benchmarks only use standard library functionality? Likewise, how resource and time intensive may we be? I'm specifically thinking about numerical operations that my users frequently use Python for - histogram generation, random number generation, changing data endianness, rotating small arrays?

**Comment by kmod** [comment]
Our goal is to test realistic software, so definitely don't feel limited to standard library functionality.  In terms of resource usage, we like to keep the runtime around 10 seconds just as a practical matter, since that's long enough to get reasonable data but short enough that it's not painful to run.  But ideally there'd be some configuration flags so that we can adjust it.  In terms of other resources, I think it's fine as long as it doesn't make the benchmark hard to run in peoples' various dev environments.

Looking forward to seeing what you come up with!
