### ISSUE TITLE
"Extended C API" package

### ISSUE THREAD

**Issue by kmod** [pyston/pyston#1230]
This is an idea for putting more of the C API behind an actual API, without breaking CPython compatibility.  If we want to upstream a Pyston change to an extension, the current status quo is to do something like

``` C
#ifdef PYSTON_VERSION
  foo = PyErr_GetExcInfoType(); // a new API function
#else
  foo = PyThreadState_GET()->exc_type; // direct field access
#endif
```

I think this is a bad situation, since the `#ifdef PYSTON_VERSION` check is pretty ugly and unfriendly, since it requires the package authors to maintain code for each implementation they want to support.  This is what should be solved by an API in the first place, but the issue is that the corresponding API functions are missing.

So the idea is: what if we created some sort of "extended C API" which includes some of these new API functions.  Maybe "sane API" is a better name since the point isn't to add new functionality but to better encapsulate the existing functionality.  Then for CPython support, we could create a header-only package that implements these new API functions on top of the direct-field-access that CPython already supports:

``` C
#ifndef IMPLEMENTATION_SUPPORTS_EXTENDED_C_API
#define PyErr_GetExcInfoType() PyThreadState_GET()->exc_type
#endif
```

and Pyston and other implementations would `#define IMPLEMENTATION_SUPPORTS_EXTENDED_C_API`.

So then if extension authors wanted to support CPython + Pyston + other implementations, they would only need to change their code to use the extended API and then add our new package to their dependency list.  Doing it as a package should make it relatively easy to depend on, as well as easy to update if we want to add new APIs to it.

We could also start adding feature-flags to this API so that extension code can check those rather than checking the implementation version.  For instance, Pyston doesn't support custom code objects yet, so we could do something like

``` C
// extended_c_api.h:
#ifndef IMPLEMENTATION_SUPPORTS_EXTENDED_C_API
#define SUPPORTS_CUSTOM_CODE_OBJECTS // CPython's version of feature flags
#endif
```

and then switch our patch to Cython to check this new flag rather than just commenting out the section.  Then we can just flip the flag on our side when we are ready to support it.

Thoughts?

**Comment by Daetalus** [comment]
Just a joke: Many years later, developers believe this proposal was an important event, marks Pyston become a strong competitor to CPython.

**Comment by Daetalus** [comment]
During support SciPy. We(my manager @navytux and I, in nexedi) build an experimental "extended C API" repo. https://github.com/Nexedi/pycapicompat. But it has slightly differences compared with the original idea.

Now it is the end of SciPy support. I think the "extended C API" package is ready, at least ready to discuss.

Thoughts? @njsmith @undingen @navytux

**Comment by kmod** [comment]
I think this looks great!  What do you / other people think of a format like this:

```C
#ifndef IMPLEMENTATION_EXTENDED_CAPI_VERSION
#define IMPLEMENTATION_EXTENDED_CAPI_VERSION 0
#endif

#if IMPLEMENTATION_EXTENDED_CAPI_VERSION < 1
static inline int PyCode_HasFreeVars(PyCodeObject *co) {
    return PyCode_GetNumFree(co) > 0 ? 1 : 0;
}

static inline void
PyFrame_SetLineNumber(PyFrameObject *f, int lineno) {
    f->f_lineno = lineno;
}
#endif
```

I think this should make things simpler by decoupling the extended-c-api project from any particular implementation version.  For example if in the next version of PyPy they want to add their own versions of these functions, they could just start setting the `IMPLEMENTATION_EXTENDED_CAPI_VERSION` flag and not have to wait for new versions of the extended-c-api package to get rolled out.  It also lets the project be implementation-agnostic in case any other implementations want to use this too.

Also, I think another candidate for a name is "high level C API".  I think "extended" makes it seem like we are adding new functionality / creating more of a bad situation, but I think "high-level" more accurately describes what it is and what the goal is.

Anyway, I'm still excited about this :)  Looking forward to getting some feedback from the library developers.
