### ISSUE TITLE
86% slower than original interpreter

### ISSUE THREAD

**Issue by flok99** [pyston/pyston#1254]
For fun and profit I ran a test-program under pyston, shedskin, pypy and the regular python interpreter.

python: 2m24.580s
pypy: 7.608s
pyston: 2m44.144s (!)
shedskin: 1.724s

Some room for improvement :-)

https://vanheusden.com/misc/blog/2016-05-19_brainfuck_compilers_compared.php

**Comment by undingen** [comment]
wow thanks for the example :+1: .
this is embarrassingly slow :blush:.
from the 186secs it takes on my machine we spend about 109secs inside LLVM compiling the functions...
that means at least on the second run it will take 73secs but still bad :-(.
I think we really don't like all this global scope accesses...

**Comment by flok99** [comment]
With all pleasure!

If it makes you feel better: perl 6 is also very slow with this code :-)



On Thu, Jun 16, 2016 at 3:11 PM, Marius Wachtler <notifications@github.com>
wrote:

> wow thanks for the example 👍 .
> this is embarrassingly slow 😊.
> from the 186secs it takes on my machine we spend about 109secs inside LLVM
> compiling the functions...
> that means at least on the second run it will take 73secs but still bad
> :-(.
> I think we really don't like all this global scope accesses...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dropbox/pyston/issues/1254#issuecomment-226480362>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADESuHj89g_1HFirWcoAZ4yQMXrCPtjmks5qMUt8gaJpZM4I3Vc4>
> .
>



-- 
www.vanheusden.com  www.slimwinnen.nl
