### ISSUE TITLE
Why not translate Python to a more advanced language？

### ISSUE THREAD

**Issue by roundsheep** [pyston/pyston#1346]
I have been working on LLVM for a few years, it is a low level language, when translate a dynamic language to LLVM, just like translate it to assembly. You wrote a Python compiler! Yes, it is a great project, this is a huge work. But there is a much simpler way, why not translate Python to C++? We have Clang, so we can translate C++ to LLVM by Clang, that is the same as this project. We know that C++11 has many advanced features, like closure, so it is not issue. But I'm not saying Shedskin or any other project just support static type, that is not really Python. At last, thanks a lot.

**Comment by kmod** [comment]
Thanks for the suggestion!  There are a lot of different variants of "Python to C/C++", would you mind talking more about the one you're proposing?  For example there's Shedskin which you mentioned, or Cython that already translates Python to C (to the Python C API).
