### ISSUE TITLE
NumPy Benchmarks

### ISSUE THREAD

**Issue by jakirkham** [pyston/pyston#1415]
Saw some mention of benchmarking NumPy performance in the last blog post. Was curious if anyone has tried running [NumPy's benchmarking suite]( https://github.com/numpy/numpy/blob/master/benchmarks/README.rst ) and compared it against CPython's and potentially [PyPy's]( https://github.com/numpy/numpy/blob/master/doc/release/1.12.0-notes.rst#added-support ) performance.

**Comment by kmod** [comment]
I took a very brief look, and it seems geared towards making sure that individual NumPy operations don't regress in performance.  For example take a look at their [linear algebra](https://github.com/numpy/numpy/blob/master/benchmarks/benchmarks/bench_linalg.py) benchmark set; each benchmark is just a single function call.

My understanding is that there's not much room to improve NumPy's performance by looking at individual operations, and the gains are by looking across operations.  But how to tackle that depends a lot on the code and what it would take to identify multiple operations and optimize them together.

**Comment by jakirkham** [comment]
It's true. Though I would argue that those are functions that have been demonstrated to be common pain points worthy of more optimization. So if one can think up a decent problem that uses a few of those operations, that should be a good test. That being said, I agree that running those benchmarks may not be very interesting.

Maybe trying some NumPy dependent projects would be more interesting. Though it may require more tweaking to Pyston to get them working as many also build their own extensions. A good candidate might be scikit-learn's [benchmarks]( https://github.com/scikit-learn/scikit-learn/tree/master/benchmarks ). This includes some interesting functions used in machine learning algorithms and would give people in this domain a good sense of where Pyston stands. Though this would require building SciPy and one would want to be sure they use a decent BLAS implementation when building all 3 (NumPy, SciPy, and scikit-learn). That said, doing this on Linux should be feasible.

Another option that might be less ambitious to get working, but would give you a better sense of how Pyston performs with NumPy, would be these [NumFOCUS benchmarks]( https://github.com/numfocus/python-benchmarks ) that grew out of discussions at a previous PyCon meeting to compare different NumPy and Python implementations as summarized in this [blog post]( http://andy.terrel.us/blog/2013/07/07/numpy-scipy-benchmarks/ ). This would allow for some comparison between different interpreters as well.

**Comment by kmod** [comment]
Oh the scikit-learn benchmarks and the NumFOCUS benchmarks look great, thanks for the links!
