### ISSUE TITLE
Is this project dead ?

### ISSUE THREAD

**Issue by skywind3000** [pyston/pyston#1426]
no update for nearly a year.

**Comment by lesshaste** [comment]
Sadly yes.

**Comment by danluu** [comment]
@skywind3000 [there's a post on the pyston blog about this](https://blog.pyston.org/2017/01/31/pyston-0-6-1-released-and-future-plans/):

> this is the last release that Dropbox is sponsoring.
> ...
> Marius and I are no longer spending our time working on Pyston and are transitioning to other projects.  The project itself remains open source and available, and we are investigating ways that the project can continue, either in whole or in part.  We are also looking into upstreaming parts of our code back to CPython, since our code is now based on theirs.

**Comment by skywind3000** [comment]
sad

**Comment by osman-masood** [comment]
Good effort though. RIP.

**Comment by corporatepiyush** [comment]
I believe it means no active support for Python 3 and later.
But does it run okay on 2.7.x ?

**Comment by xxllp** [comment]
sad ~~~

**Comment by 007lva** [comment]
Well, https://github.com/RustPython/RustPython is getting some traction right now.
