### ISSUE TITLE
AST Interpreter 

### ISSUE THREAD

**Issue by sirinath** [pyston/pyston#1430]
Can this take the approach Graal is taking so other language font ends can be added?

**Comment by kmod** [comment]
Maybe, but what would be the benefit over Graal itself?

But also Pyston v2 doesn't have an AST interpreter so we're unlikely to move in that direction.

**Comment by sirinath** [comment]
Yet another AST interpreter may not be better than Graal. But following might be an approach to beat it. Ideally, the final implementation should be faster then Graal and Eclipse OMR, otherwise, there is no point. So I believe the Pyston 2.0 exercise should look at how to beat Graal and Eclipse OMR in implementing a language like Python with the flexibility to implement any other language also more optimally than existing implementations.

I think the best approach would be:
- have declarative [rewriting](https://en.wikipedia.org/wiki/Rewriting) rules which can be used for
  - parsing
   - support both
     - text and
     - binary 
  - optimisations
  - code generation
  - code execution
- the language representing the rules itself will be defined in the same language so the new version can be easily defined
- if the system is such defined to save a meta file then using it and the resulting code can be deoptimised and reversed engineered to produce a previous abstraction
- for a given set of rules the resulting code would be probably the most optimal reduction of the given rules
  - better or more detail rules would mean more optimal output can be produced
- which means the rule engine implementation also would be optimal as it is defined the same way

Given a grammar and parsing rules then AST is produced. Given another rewriting ruleset this is optimised. Another ruleset will covert it into IR. Another ruleset will produce JIT or AOT code. The rewriting engine will be the parser, Interpreter or VM/AST Interpreter/JITer or AOT Compiler.

Also, there will be no hard phases. The interdependency between the rules will determine the phases.

This way any language can be JITed or compiles AOT.

Implementing a rewriting rule engine would be the most optimal way to approach this and perhaps better than Graal.

**Comment by kmod** [comment]
This would be really cool!  Not really the direction we've gone with Pyston 2 but we would love to see someone do this.
