### ISSUE TITLE
Building from sources fails because of private repository

### ISSUE THREAD

**Issue by alexprengere** [pyston/pyston#1431]
Trying to build Pyston from sources on the latest Fedora (33). Looking at this step:
```
git submodule update --init --recursive build_deps
```
This fails because `https://github.com/pathscale/libunwind.git` looks like a private repository.

A few other remarks:
+ [the installation procedure](https://github.com/pyston/pyston/blob/py3/docs/INSTALLING.md) would be a bit more discoverable if it was located at top level
+ the default branch is master, which is empty, and everything seems to be in the py3 branch. This is fine, but it would make the repository easier to browse if py3 was set as the default branch on github

EDIT: it looks like I misunderstood how things work. For those who will make the same mistake: V2 is closed source, and the installation procedure I pointed to is actually for V1, and may be outdated.

**Comment by kmod** [comment]
Sorry, I know this misled multiple people, and we're trying to make the situation more clear.
