### ISSUE TITLE
Packages for Fedora

### ISSUE THREAD

**Issue by alexprengere** [pyston/pyston#1432]
Would it be possible to provide packages for Fedora as well as Ubuntu? Thanks a lot!

**Comment by kmod** [comment]
We'd love to! I don't think Marius or I have any experience with Fedora though, much less its packaging. If you have any pointers on how to do that it will make this happen faster.

**Comment by adamw-linadm** [comment]
Instead of making packages only for fedora, make package for centosa/redhata/fedora together :)
You can use the fpm tool for this, which is very friendly and works without problems. https://fpm.readthedocs.io/en/latest/source/rpm.html

**Comment by alexprengere** [comment]
I was about to suggest fpm as well 😉 
I just tried it on Fedora 33, using the latest fpm `1.11.0`, unfortunately it does not work out of the box (perhaps I missed something).

```bash
$ fpm -s deb -t rpm pyston_2.0_amd64_20.04.deb
Created package {:path=>"pyston-2.0-1.x86_64.rpm"}
$ sudo rpm -ivh pyston-2.0-1.x86_64.rpm
error: Failed dependencies:
	libbz2-1.0 is needed by pyston-2.0-1.x86_64
	libc6 >= 2.29 is needed by pyston-2.0-1.x86_64
	libcrypt1 >= 1:4.1.0 is needed by pyston-2.0-1.x86_64
	libdb5.3 is needed by pyston-2.0-1.x86_64
	libffi7 >= 3.3~20180313 is needed by pyston-2.0-1.x86_64
	libgdbm6 >= 1.16 is needed by pyston-2.0-1.x86_64
	liblzma5 >= 5.1.1alpha+20120614 is needed by pyston-2.0-1.x86_64
	libncursesw6 >= 6 is needed by pyston-2.0-1.x86_64
	libreadline8 >= 7.0~beta is needed by pyston-2.0-1.x86_64
	libsqlite3-0 >= 3.7.15 is needed by pyston-2.0-1.x86_64
	libssl1.1 >= 1.1.1 is needed by pyston-2.0-1.x86_64
	libtcl8.6 >= 8.6.0 is needed by pyston-2.0-1.x86_64
	libtinfo6 >= 6 is needed by pyston-2.0-1.x86_64
	libtk8.6 >= 8.6.0 is needed by pyston-2.0-1.x86_64
	libuuid1 >= 2.20.1 is needed by pyston-2.0-1.x86_64
	tk8.6-blt2.5 >= 2.5.3 is needed by pyston-2.0-1.x86_64
	zlib1g >= 1:1.2.0 is needed by pyston-2.0-1.x86_64
```
Libraries like `liblzma5` do not exist under that name on Fedora (I have `xz-devel` installed).

**Comment by JordyScript** [comment]
Maybe packaging as a flatpak could help? Those can be used by many different distros. Would probably solve this problem for everyone who wants to use it.

**Comment by ytrezq** [comment]
What about providing a static python binary which would work accross all Linux distributions?

**Comment by undingen** [comment]
We will likely provide a portable archive (which will also work on fedora) at the next small release.

**Comment by undingen** [comment]
We don't have fedora packages but we have now a release archive which comes with all dependencies and runs on fedora - no installation required.
Download pyston_2.1.tar.gz from https://github.com/pyston/pyston/releases/tag/v2.1
