### ISSUE TITLE
Is there a exec file of pyston v2.0 for windows10？

### ISSUE THREAD

**Issue by colinxu2020** [pyston/pyston#1437]

**Comment by undingen** [comment]
Unfortunately we don't support windows at this time.
It seems to work inside WSL2 but we haven't really tested it.
Would be interested to hear if this is an option for you.

**Comment by Gabrielcarvfer** [comment]
It does work with WSLv1, but suffers from same issue Qt and a few other libraries have, as reported in https://github.com/microsoft/WSL/issues/3023.
The following command solves the exec issue:
`sudo strip --remove-section=.note.ABI-tag /usr/bin/pyston`

**Comment by undingen** [comment]
Thanks for looking into the WSLv1 issue.

**Comment by colinxu2020** [comment]
thinks,I Know.
