### ISSUE TITLE
How to use command line start-up applications with pyston?

### ISSUE THREAD

**Issue by GoodManWEN** [pyston/pyston#1442]
Hi there,

Really appreciate your work .I got a probelem using CLI startup apps such as `gunicorn` , which is a pypi package defined a "entry point" in `setup.py` , so that we can start-up a gunicorn app in CLI with commands like `gunicorn app:main -w 10` .

However I find there's no link to pyston's gunicorn if I'm using `pip-pyston install gunicorn` command installing this package.What should I do if I want a pyston environment gunicorn?

**Comment by kmod** [comment]
Thanks for checking us out! Can you give some details about what you did?

I tried:
```
$ sudo pip-pyston install gunicorn
$ which gunicorn
/usr/bin/gunicorn
$ head -n1 /usr/bin/gunicorn
#!/usr/bin/pyston3.8
```

If you used `pip-pyston --user`, it installs in `$HOME/.local/bin/gunicorn` like pip does, though this is not on your PATH by default.

If you use a virtual environment (recommended) it should go into the `bin` directory of the environment and it should be locateable if you activate the environment.

**Comment by GoodManWEN** [comment]
Thanks for your kind reply , very helpful ,venv perfectly solved my problem.

The problem may caused by some kind of version conflict ,since before install pyston , there's already a python3.8 (with gunicorn) environment in my ubuntu20.04 os. I had thought it would be a overwrite if I install gunicorn again with pip-pyston , but it seems not. Good news is with venv I could finally startup a pyston gunicorn server.

However there's also bad news , unfortunately according to my test a moment ago (I setup a asynchronous gunicorn echo server with aiohttp) , there seems to have no significant performance difference between server based on pyston2.1 and python3.8 , nomatter if I'm using python's built-in event loop or uvloop. Sometimes pyston2.1 get faster for a few percent and sometimes slower.

Anyway, thanks for work of you guys and thanks for your help in this issue.

**Comment by kmod** [comment]
That's interesting about performance not being better, we'll take a look!  I'm not familiar with gunicorn, but if the main part of the work is done in a C extension then we wouldn't expect to see a speedup.

How were you benchmarking gunicorn?  We'd like to put together a benchmark for it

**Comment by GoodManWEN** [comment]
In my opinion is definately better include gunicorn & aio features in your benchmark blogs , since in 2021 famous websites such as TechEmpower are using gunicorn for benchmarks either . [source](https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Python/fastapi/fastapi-orjson.dockerfile)

All my operation is as follow:

1\ Create enviornments 
```sh
># python3 -m venv py38env
># source py38env/bin/activate
># pip install aiohttp gunicorn uvloop
```
same as pyston
```sh
># pyston -m venv ps21env
># source ps21env/bin/activate
># pip install aiohttp gunicorn uvloop
```

2\ Test file
Create a simple echo server  as follow:`test.py`
```Python
# test.py
from aiohttp import web

async def hello(request):
    return web.Response(text="Hello, world")

async def main():
    app = web.Application()
    app.add_routes([web.get('/', hello)])
    return app
```
3\ Start with gunicorn for both using built-in event loop and uvloop , as I got a laptop with four core processer , there'll be four preforked process serving , and the client thread number will be 4 + 1
```
# To start with python's builtin event loop
># gunicorn test:main --bind 0.0.0.0:8000 -w 4 --worker-class aiohttp.GunicornWebWorker 
# To start with uvloop
># gunicorn test:main --bind 0.0.0.0:8000 -w 4 --worker-class aiohttp.GunicornUVLoopWebWorker 
```

4\ I'm using wrk for stress testing , test results as follows:
Python3.8 + built-in event loop
```
root@vm:/home/vm# wrk -t5 -c100 -d20s http://127.0.0.1:8000
Running 20s test @ http://127.0.0.1:8000
  5 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     4.64ms    1.60ms  24.45ms   79.72%
    Req/Sec     4.37k   697.84     6.22k    63.80%
  434483 requests in 20.02s, 73.76MB read
Requests/sec:  21704.59
Transfer/sec:      3.68MB
```
Pyston2.1 + built-in event loop ( 0.99% faster)
```
root@vm:/home/vm# wrk -t5 -c100 -d20s http://127.0.0.1:8000
Running 20s test @ http://127.0.0.1:8000
  5 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     7.17ms   27.70ms 511.43ms   99.10%
    Req/Sec     4.45k     1.62k   12.27k    74.62%
  440581 requests in 20.10s, 74.79MB read
Requests/sec:  21919.48
Transfer/sec:      3.72MB
```

Python3.8 + uvloop
```
root@vm:/home/vm# wrk -t5 -c100 -d20s http://127.0.0.1:8000
Running 20s test @ http://127.0.0.1:8000
  5 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.83ms    1.37ms  28.57ms   77.25%
    Req/Sec     7.22k     1.31k   10.48k    58.10%
  718989 requests in 20.03s, 122.05MB read
Requests/sec:  35898.56
Transfer/sec:      6.09MB
```

Pyston2.1 + uvloop (about 7.7% slower)
```
root@vm:/home/vm# wrk -t5 -c100 -d20s http://127.0.0.1:8000
Running 20s test @ http://127.0.0.1:8000
  5 threads and 100 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     3.12ms    1.85ms  20.78ms   74.25%
    Req/Sec     6.66k     2.34k   14.20k    70.10%
  663151 requests in 20.02s, 112.57MB read
Requests/sec:  33130.11
Transfer/sec:      5.62MB
```

As far as I know , if neglect the uvloop , both gunicorn and aiohttp are wrote in pure-python , so I'm expecting a great improve, however the result seems not.

**Comment by kmod** [comment]
Ah fascinating.  I'm seeing some C extensions but they're definitely not the majority of the time so I'm not sure what's going on here.  We'll take a look, thanks for reporting and giving us a benchmark!
