### ISSUE TITLE
callattr with descriptor cannot be re-written

### ISSUE THREAD

**Issue by tjhance** [pyston/pyston#189]
Right now, we cannot re-write things of the form

``` python
a.b()
```

If accessing `a.b` requires a descriptor lookup.

We _are_ able to re-write an attribute look-up that accesses a descriptor and a call, so we could re-write this code:

``` python
attr = a.b
attr()
```

The difference is that in the first case, we don't use a getattr and a call; we use a callattr (typically this is an optimization, because you can often take short-cuts when accessing an attribute that you know you're only going to use to call - you don't have to wrap the function in an instancemethod).

Re-writing the callattr is a bit like re-writing a getattr followed by a call. Both of these can be re-written on its own, but when we try to re-write them together, we fail. The reason is that re-writing the callattr involves: some guards, and then a call (to `__get__`), then more guards and then another call (to the function attribute).

But: we can't do guards after a call, since a call could have side-effects.

So, we need something like support for gurading after side-effects, or a way to break up the callattr into a separate getattr and call that can be re-written on their own, or something.

**Comment by toshok** [comment]
I've been curious about this, so I added some instrumenting in `getattrInternalGeneric`, and see this for `django_template.py`:

```
                                                                           total  1456
           minibenchmarks/../test/integration/django/django/template/base.py:469  231 (16%)
              minibenchmarks/../test/integration/django/django/utils/text.py:429  108 (7%)
           minibenchmarks/../test/integration/django/django/template/base.py:427  96 (7%)
           minibenchmarks/../test/integration/django/django/template/base.py:449  72 (5%)
           minibenchmarks/../test/integration/django/django/template/base.py:430  64 (4%)
```

all of the base.py lines are of the same form:

```
base.py:469 while i < len(subject) and subject[i] != subject[p]:
base.py:427 while i < len(subject) and subject[i] not in (' ', '\t'):
base.py:449 while i < len(subject) and subject[i] not in (' ', '\t'):
base.py:430 while i < len(subject) and subject[i] in (' ', '\t'):
text.py:429 if s[0] not in "\"'" or s[-1] != s[0]:
