### ISSUE TITLE
thread_memory_model_test is flaky

### ISSUE THREAD

**Issue by tjhance** [pyston/pyston#367]

**Comment by tjhance** [comment]
So I took a minute to look into this and this assert from `core/thread_utils.h` is firing:

```
        // I assume this destructor gets called on the same thread
        // that this data is bound to:
        assert(self->map.count(pthread_self()));
```

I guess this assumption must not be true?

**Comment by kmod** [comment]
I ran this a very large number of times and I haven't seen it fail :(  are you getting this with just a plain `make run_thread_memory_model_test`?

**Comment by tjhance** [comment]
I ran `make check_thread_memory_model_test`, if that makes any difference

**Comment by kmod** [comment]
Have you seen this lately?

**Comment by tjhance** [comment]
Yep, still see it. It isn't really bothering me, since I've figured out how to work around it, but yes, it is still happening.
