### ISSUE TITLE
Get more CPython tests working

### ISSUE THREAD

**Issue by kmod** [pyston/pyston#450]
The cpython test suite is a good source of tasks; we're currently failing 92 of 142 tests, and a lot of them for fairly simple reasons.  ex `make run_test_pow` runs the "test_pow.py" CPython test, and fails with `NameError: global name 'pow' is not defined`.

I think the best source of info on the state of the testsuite is [here](https://github.com/dropbox/pyston/blob/master/test/CPYTHON_TEST_NOTES.md).

**Comment by arbipher** [comment]
It seems a good start to me.

**Comment by kmod** [comment]
I just took another pass over the [notes doc](https://raw.githubusercontent.com/dropbox/pyston/master/test/cpython/NOTES.org) and it should be current again.  I also added the "probably easy" label here since there are a bunch of easy tasks in the list, though it seems like there are also some quite hard ones too.

I'm not sure happy with the current way of managing the documentation on the failing tests (ie the text file in the repo), but it feels like there'd be drawbacks to mass-importing it into github issues so for now I don't feel like going through that process.

**Comment by deronnax** [comment]
the notes you link to are 404. Maybe you're refering to https://github.com/dropbox/pyston/blob/master/test/CPYTHON_TEST_NOTES.md ? Maybe you should update the link you give

**Comment by undingen** [comment]
thanks :+1:  I edited the comments to refer to the correct file :-)

**Comment by deronnax** [comment]
you linked to the very raw file which is pretty unpleasant to read. I think you would prefer to link the not-raw version, like the link I gave :)
