### ISSUE TITLE
Support PyEval_SaveThread

### ISSUE THREAD

**Issue by rudi-c** [pyston/pyston#778]
`PyEval_SaveThread` along with related functions in `capi.cpp` currently throw an `Py_FatalError("Unimplemented");` exception.

**Comment by kmod** [comment]
I think the trickiness here is I'm not sure what the return value of those functions is supposed to represent.  Can you save the thread state from one thread and resume it on another?  Are there certain things that are supposed to be defined in it?  Anyway, to punt on those issues for now, we added `beginAllowThreads` / `endAllowThreads` functions which handle the common case of just releasing/acquiring the GIL.
