### ISSUE TITLE
Use static type annotations

### ISSUE THREAD

**Issue by zyga** [pyston/pyston#9]
Hey.

I think you should look at mypy (http://www.mypy-lang.org/) and add support to optional static type annotations. Those can be expressed directly on python3 and with decorators / docstrings on python2.7.

This could allow the compiler to offer aggressive optimizations where a binding can only bind to particular subset of types (various numeric types) and the compiler can report an error (or discard the annotation and issue a warning) when declarations are conflicting actual usage.

**Comment by datnamer** [comment]
Another benefit: Perhaps fully typed modules  could be emitted  as precompiled  llvm. This could allow these modules to be compiled to web assembly and run client side without javascript.
